DROP TABLE QNA_TB;
DROP SEQUENCE SEQ_QSEQ;

CREATE SEQUENCE SEQ_QSEQ;
CREATE TABLE QNA_TB
(
    SEQ_Q         NUMBER        NOT NULL, 
    GROUPSEQ_Q    NUMBER    NOT NULL, 
    ORDER_Q       NUMBER    NOT NULL, 
    TITLET_Q      VARCHAR2(5)    NOT NULL, 
    TITLE_Q       VARCHAR2(40)    NOT NULL, 
    CONTENT_Q     VARCHAR2(1000)    NOT NULL, 
    EMAIL         VARCHAR2(100)    NOT NULL, 
    DATE_Q        DATE        NOT NULL, 
    CONSTRAINT QNA_TB_PK PRIMARY KEY (SEQ_Q)
);




SELECT * FROM QNA_TB;


INSERT INTO QNA_TB VALUES(SEQ_QSEQ.NEXTVAL,1,1,'U','TITLE','HAPPY','USER01',SYSDATE);
INSERT INTO QNA_TB VALUES(SEQ_QSEQ.NEXTVAL,1,2,'U','TITLE','HAPPY','USER01',SYSDATE); 

