DROP SEQUENCE MYNOSEQ;
DROP TABLE MYMYBOARD;

CREATE SEQUENCE MYNOSEQ;
CREATE TABLE MYMYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYMYBOARD VALUES(MYNOSEQ.NEXTVAL, '관리자','스프링 테스트', 'spring mvc 어렵다...', SYSDATE);

SELECT MYNO, MYNAME, MYTITLE, MYCONTENT, MYDATE
FROM MYMYBOARD
ORDER BY MYNO DESC;